paths-ignore:
  - "node_modules/**"
  - ".next/**"
  - "coverage/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"

patterns:
  - name: Vercel Token
    pattern: "VERCEL_TOKEN"
  - name: Google API Key
    pattern: "GOOGLE_API_KEY"
  - name: Database URL
    pattern: "DATABASE_URL"
