version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:14
    container_name: postgres
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitecall
    ports:
      - 5432:5432
