name: Branch Protection

on:
  pull_request:
    branches: [main]

jobs:
  protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Required Reviews
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvedReviews = reviews.filter(review => review.state === 'APPROVED');

            if (approvedReviews.length < 1) {
              core.setFailed('At least one approved review is required');
            }
