name: Branch Protection

on:
  pull_request:
    branches: [main]

jobs:
  protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Required Reviews
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Skip check for draft PRs
            if (pr.draft) {
              console.log('Draft PR - skipping review check');
              return;
            }

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvedReviews = reviews.filter(review => review.state === 'APPROVED');

            // Allow self-review for solo development
            if (pr.user.login === pr.base.repo.owner.login) {
              console.log('Repository owner PR - skipping review check');
              return;
            }

            if (approvedReviews.length < 1) {
              core.setFailed('At least one approved review is required');
            }
